### ISSUE TITLE
dismiss报错

### ISSUE THREAD

**Issue by gincoo** [binIoter/GuideView#30]
`       java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchConfigurationChanged(android.content.res.Configuration)' on a null object reference
                                                                                      at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1315)
                                                                                      at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1315)
                                                                                      at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1315)
                                                                                      at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1315)
                                                                                      at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1315)
                                                                                      at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1315)
                                                                                      at android.view.ViewRootImpl.updateConfiguration(ViewRootImpl.java:3585)
                                                                                      at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3753)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                      at android.os.Looper.loop(Looper.java:156)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)`

**Comment by binIoter** [comment]
能贴一下你使用的代码吗？
